// Activities illustrate how a goal can shape lessons; package inclusions match packages.js.
export const COURSE_SLIDES = {
  en: [
    { id: 'interviews', label: 'Job interviews', tag: 'Specialist English · 1:1', title: 'Tell your story with confidence.', body: 'Prepare for the conversation that could change your working life. Bring a role you are aiming for and practise explaining what you can offer.', points: ['Rehearse interview questions and follow-up conversations with your teacher.', 'Turn your experience into clear examples, with vocabulary relevant to your role.', 'Work on answers, pronunciation and delivery, then try again with feedback.'], example: 'A lesson could focus on: “Tell me about a challenge you handled.”', alt: 'A woman rehearses a job interview with an online tutor.' },
    { id: 'exams', label: 'Exam preparation', tag: 'Specialist English · 1:1', title: 'Give your exam preparation a plan.', body: 'Tell us which exam you are working towards and when. Start from your current level, then focus lesson time on the skills and task types you need to practise.', points: ['Agree priorities for speaking, writing, reading or listening.', 'Practise exam-style tasks and discuss how to structure your response.', 'Use teacher feedback to identify what to improve before your next attempt.'], example: 'A lesson could focus on: a timed speaking response and a clearer second attempt.', alt: 'An adult learner works through exam practice papers beside a laptop.' },
    { id: 'relocation', label: 'Life abroad', tag: 'Specialist English · 1:1', title: 'Feel more at home in English.', body: 'Moving abroad brings a lot of first conversations. Practise the everyday situations ahead of you, with time to ask questions and find the words that feel natural.', points: ['Role-play renting a home, making appointments and asking for help.', 'Practise explaining a problem and checking that you have understood.', 'Build the small-talk skills that help you meet neighbours and colleagues.'], example: 'A lesson could focus on: calling a landlord to explain a repair you need.', alt: 'Two women chat outside a London cafe, illustrating everyday English abroad.' },
    { id: 'work', label: 'English at work', tag: 'Specialist English · 1:1', title: 'Make your point at work.', body: 'Bring the communication your job calls for. Shape your lessons around the meetings, presentations and messages you want to handle more clearly.', points: ['Practise giving updates, asking questions and disagreeing politely in meetings.', 'Rehearse a presentation and respond to questions about your ideas.', 'Work on useful language for emails and conversations in your field.'], example: 'A lesson could focus on: explaining a project delay and proposing the next step.', alt: 'A professional presents an idea to colleagues in a modern office.' },
    { id: 'groups', label: 'Small-group courses', tag: 'Live online · up to 4 students', title: 'More voices. More ways to practise.', body: 'Learn with classmates at a similar level and a teacher to guide the conversation. A small group gives you different people to listen to, respond to and learn alongside.', points: ['Build confidence through discussion, shared tasks and everyday role-play.', 'Practise taking turns, asking follow-up questions and explaining your opinion.', 'Keep a regular rhythm with 60-minute lessons on a fixed group timetable.'], example: 'Explore the current course dates, levels and available groups on the pricing page.', alt: 'A learner joins a small online English class with a teacher and classmates.' },
    { id: 'plan', label: 'Your learning plan', tag: 'Specialist programmes · 6, 12 or 24 lessons', title: 'A clear goal. Support along the way.', body: 'Start with a diagnostic placement call and a specialist CEFR outcome plan. Choose the programme length that fits your goal and the time you want to give it.', points: ['Sprint: 6 × 60-minute specialist lessons, with review notes after each session.', 'Track: 12 × 60-minute specialist lessons, including two writing or speaking reviews.', 'Mastery: 24 × 60-minute specialist lessons, with monthly review and lesson notes.'], example: 'Your starting level and goals guide the plan; your teacher helps you see what to work on next.', alt: 'An adult learner reviews study notes during an online meeting with a teacher.' },
  ],
  pl: [
    { id: 'interviews', label: 'Rozmowy o pracę', tag: 'Angielski specjalistyczny · 1:1', title: 'Opowiedz o sobie z pewnością.', body: 'Przygotuj się do rozmowy, która może zmienić Twoją pracę. Przynieś ofertę, która Cię interesuje, i przećwicz, jak przedstawić swoje doświadczenie.', points: ['Przećwicz pytania rekrutacyjne i pytania uzupełniające z lektorem.', 'Zamień swoje doświadczenia w jasne przykłady ze słownictwem związanym ze stanowiskiem.', 'Pracuj nad odpowiedziami, wymową i sposobem mówienia, a potem spróbuj ponownie po wskazówkach lektora.'], example: 'Przykładowy temat lekcji: „Opowiedz o wyzwaniu, z którym sobie poradziłeś”.', alt: 'Kobieta ćwiczy rozmowę kwalifikacyjną z lektorem online.' },
    { id: 'exams', label: 'Przygotowanie do egzaminu', tag: 'Angielski specjalistyczny · 1:1', title: 'Podejdź do egzaminu z planem.', body: 'Powiedz nam, do jakiego egzaminu się przygotowujesz i kiedy go zdajesz. Zaczniemy od Twojego poziomu i skupimy lekcje na umiejętnościach oraz typach zadań, które potrzebujesz przećwiczyć.', points: ['Ustal priorytety w mówieniu, pisaniu, czytaniu lub słuchaniu.', 'Ćwicz zadania w stylu egzaminacyjnym i omawiaj strukturę odpowiedzi.', 'Korzystaj z informacji zwrotnej lektora, aby wiedzieć, co poprawić przy kolejnej próbie.'], example: 'Przykładowy temat lekcji: wypowiedź na czas i druga próba po omówieniu odpowiedzi.', alt: 'Dorosły uczeń rozwiązuje zadania egzaminacyjne przy laptopie.' },
    { id: 'relocation', label: 'Życie za granicą', tag: 'Angielski specjalistyczny · 1:1', title: 'Poczuj się swobodniej za granicą.', body: 'Przeprowadzka oznacza wiele pierwszych rozmów. Przećwicz codzienne sytuacje, które Cię czekają, z czasem na pytania i szukanie naturalnych sformułowań.', points: ['Odgrywaj rozmowy o wynajmie mieszkania, umawianiu wizyt i proszeniu o pomoc.', 'Ćwicz wyjaśnianie problemów i upewnianie się, że dobrze rozumiesz rozmówcę.', 'Rozwijaj swobodne rozmowy, które pomagają poznawać sąsiadów i współpracowników.'], example: 'Przykładowy temat lekcji: telefon do właściciela mieszkania w sprawie naprawy.', alt: 'Dwie kobiety rozmawiają przed londyńską kawiarnią.' },
    { id: 'work', label: 'Angielski w pracy', tag: 'Angielski specjalistyczny · 1:1', title: 'Przekazuj swoje pomysły jasno.', body: 'Przynieś sytuacje komunikacyjne ze swojej pracy. Dopasuj lekcje do spotkań, prezentacji i wiadomości, z którymi chcesz radzić sobie pewniej.', points: ['Ćwicz omawianie postępów, zadawanie pytań i uprzejme wyrażanie odmiennego zdania.', 'Przećwicz prezentację oraz odpowiedzi na pytania dotyczące swoich pomysłów.', 'Pracuj nad językiem przydatnym w wiadomościach i rozmowach w Twojej branży.'], example: 'Przykładowy temat lekcji: wyjaśnienie opóźnienia w projekcie i zaproponowanie kolejnego kroku.', alt: 'Specjalistka przedstawia pomysł współpracownikom w biurze.' },
    { id: 'groups', label: 'Kursy w małych grupach', tag: 'Online na żywo · do 4 osób', title: 'Więcej rozmówców. Więcej praktyki.', body: 'Ucz się z osobami na podobnym poziomie i lektorem, który prowadzi rozmowę. W małej grupie słuchasz różnych osób, odpowiadasz im i uczycie się od siebie.', points: ['Buduj pewność siebie przez dyskusje, wspólne zadania i scenki z życia.', 'Ćwicz zabieranie głosu, pytania uzupełniające i wyrażanie własnej opinii.', 'Utrzymuj regularny rytm dzięki 60-minutowym lekcjom w stałym grafiku grupy.'], example: 'Sprawdź aktualne terminy, poziomy i dostępne grupy na stronie z cenami.', alt: 'Uczestnik dołącza do małej grupy na lekcji angielskiego online.' },
    { id: 'plan', label: 'Twój plan nauki', tag: 'Programy specjalistyczne · 6, 12 lub 24 lekcje', title: 'Jasny cel. Wsparcie na każdym etapie.', body: 'Zacznij od rozmowy diagnozującej poziom i specjalistycznego planu celów CEFR. Wybierz długość programu dopasowaną do celu i czasu, który chcesz poświęcić na naukę.', points: ['Sprint: 6 lekcji specjalistycznych po 60 minut i notatki podsumowujące po każdej sesji.', 'Track: 12 lekcji specjalistycznych po 60 minut, w tym dwie oceny wypowiedzi pisemnej lub ustnej.', 'Mastery: 24 lekcje specjalistyczne po 60 minut, comiesięczny przegląd postępów i notatki z lekcji.'], example: 'Twój poziom i cele wyznaczają plan, a lektor pomaga ustalić, nad czym pracować dalej.', alt: 'Dorosła osoba omawia notatki i plan nauki z lektorem online.' },
  ],
}
